version: '2'

services:

### Selenium Server Container ###########################
    sel:

        # image: selenium/standalone-firefox-debug
        # Rebuilt with different password
        # selenium-custom/README.md
        image: larryeitel/standalone-firefox-debug
        ports:
            - 4444:4444
            - 5900:5900

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                # The following are ignored. They are hardcoded throughout.
                - INSTALL_MONGO=false
                - INSTALL_XDEBUG=true
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_WORKSPACE_SSH=true
                - INSTALL_GIT_TOWN=true
                - INSTALL_LARAVEL_SPARK=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.18.0.1"
        ports:
           - "2200:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                # The following are ignored. They are hardcoded throughout.
                - INSTALL_MONGO=false
                - INSTALL_XDEBUG=true
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=true
                - INSTALL_AEROSPIKE_EXTENSION=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.18.0.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"


### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/includes/:/etc/nginx/includes
            - ./nginx/sites-available/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm


### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            # MYSQL_DATABASE: homestead
            # MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/laravel

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql:rw
            - ./data/sessions:/sessions
